### ISSUE TITLE
Asplite merge or extend with other framework

### ISSUE THREAD

**Issue by mangius** [aspLite/aspLite#1]
Hello Cooreman,
do you think that's even possible to merge (or extend) your framework with the features offered by asp-ajaxed (jquery version from github /damsfx/asp-ajaxed)? 
I have some old applications that I could improve with your new useful and well-written framework.
Thanks

**Comment by PieterCooreman** [comment]
Hi, I have never used asp-ajaxed, so i couldn't tell at this point. It looks like an interesting thing to look into. Thank you for this suggestion.

**Comment by PieterCooreman** [comment]
Hello Mangius, I have given this some time and I had a closer look at Ajaxed. It's an interesting idea. At this point however, it's important to draw a strong line between the aspLite core engine and its plugins. I'd rather keep the core engine very thin. One example: today, datatables would typically be done using JavaScript, rather than large VBScript classes drawing tables. It would be a very interesting exercise however to make a list of the "best things of Ajaxed" and turn these into a single aspLite plugin. But as I have never used Ajaxed, I'm not enough familiar with its strengths. Are you?

**Comment by mangius** [comment]
Hello Pieter,
Ajaxed was the first, and maybe the only one, framework with complete built-in ajax support. It's an old project no longer maintained but has some features that make it modern and very useful for interactive web applications. I have used it from his first release in 2008. As the original release use only prototype as javascript library, with Damien MATHIEU we added a choise of which library to use between prototype or jquery and fixed some old issues, nothing else. Ajaxed has some class for drawing tables or controls "server side", but all the interactions are done with javascript and callback technique provided by javascript class (the core of ajaxed) that is a very solid solutions for applications that process a lot of data or just they need a modern look. For example, ajax callback technique is very useful for all types of web forms.
Now it would need an update and your nice Asplite is the right solutions to add some features not present in ajaxed. Doing the opposite would also be a great idea, it could become something remarkable for those who still have to develop in classic asp (and are more than you imagine). But I think I have not the technical skills to help you completely.
Here you can find the original version with complete docs: http://www.asp-ajaxed.org/
If you want I can tell you what are the most useful functions or classes used over time. But I think that is difficoult to put together "best things of Ajaxed" in once plugin. As i can I'm available to assist you if necessary.
Greetings

**Comment by PieterCooreman** [comment]
I agree... This ajax callback (with JSON output from the asp page) seems like a very interesting idea. I must admit though that I am not very familiar with Ajax. The demos in aspLite show a more "beginnner" or "pragmatic" approach when it comes to Ajax. aspLite already ships with a JSON plugin by [rcdmk](https://github.com/rcdmk/aspJSON). I'm wondering to what extend that plugin can already be used to achieve more or less the same functionality. To be honest , I'm not very familiar with JSON either. 

My main concern is not to mix JavaScript, HTML and ASP (like in Ajaxed). I don't want a classic ASP framework to be limited to jQuery, prototype or any other (Vue, React...) JavaScript framework. An ASP framework has to operate completely independent from JavaScript frameworks. Therefore, JSON seems like the perfect protocol for data transfer.

I need to study Ajax and JSON better before I can take this to a higher level in aspLite... I'm more like a back-end database developer. I welcome any suggestion....

**Comment by mangius** [comment]
Hello Pieter,
you're right, Ajaxed is limited to jquery or prototype. One important aim would be to rewrite the core of Ajaxed (class_ajaxedPage) in pure javascript.
The most important feature of Ajaxed is the core javascript-callback, anything else can be replaced. This mechanism is important because it easily ensures controlled security on the server side. Json protocol is ideal for web services, but require some difficult attentions regarding safety. 
I wrote a few applications web-services oriented using classic asp on server side and an interesting and complete VBA client-side framework that use json as main protocol (from github: VBA-tools/VBA-Web ) but it contains some security classes that are very difficult to use with asp. I think there are the same problems with javascript. If you want i can send you an example.

**Comment by PieterCooreman** [comment]
The real question is if it still makes sense to develop a server-sided Ajax framework when all JavaScript frameworks come with a very solid Ajax integration themselves. I am very impressed by [DataTables](https://demo.asplite.com/demo.asp?e=datatables). It works with both regular html and json data. DataTables comes with its own Ajax implementation, with the option to do server-side sorting, paging, CRUD, etc. I found another library named [JSON2HTML](http://json2html.com/) that does nothing but convert json data to any html construct. I added some examples to https://demo.asplite.com. I'm new to all this, so I expect to learn a lot in the coming days/weeks. I am about to look into React, Vue and Angular and see what classic ASP *could* mean for these frameworks...

**Comment by mangius** [comment]
When I started developing interactive web applications I used dhtmlx (first release), very powerful (free gnu gpl version), but immediately had problems with applications that required authentication or authorization. It was impossible maintain a session state with Ajax, so I was forced to authenticate myself with every operation. I don't know if this was a limit of dhtmlx only, but same problems occurs with other framework like vba-web, where however this behavior is expected. With Ajaxed is possible maintain session state server-side via asp session, so i decided to use Ajaxed which has a similar datatable class. 
Since Ajaxed is no longer maitained, it makes sense to use it only if nothing better is found or if is possible to rewrite it with other modern features like the ones you included in Asplite.

**Comment by PieterCooreman** [comment]
I have meantime imported the Ajaxed JSON class as a plugin in aspLite. It works much faster than the aspJson plugin I tested so far. I have also developed the ServerSide code for browsing large DataTables: https://demo.asplite.com/demo.asp?e=datatables_ssp. This page browses/sorts/searches 50.000 records in an Access database. But you barely notice that. It's very fast. I'm sure Ajaxed comes with some more very nice and well developed features. I will take my time to study its strengths.

**Comment by mangius** [comment]
Hello Pieter,
I noticed you're a night owl like me :-)
To better explain what I told you about sessions and authorizations I'm making a test environment with a clone of a simple application as example. The database contains real data, so how can I send your login credentials?

**Comment by PieterCooreman** [comment]
Mangius, I understand the session-state problem when using older technology like Flash. Today all Ajax implementations keep session-state intact (by default). 

You can send me an email via info@quickersite.com

**Comment by PieterCooreman** [comment]
I think for aspLite it's getting clear to me that there are 2 main domains to focus on:

1. Facilitate user-interaction with an Ajax formbuilder (including file uploads, rich text editors, jQueryUI, generate forms from datasets, etc). I started that development already.

2. Display data via datatables - with or without a plugin like [DataTables](https://datatables.net/). That development has started as well. 

Both rely on a good json implementation. I therefore consider to include a solid (and fast!) json-writer in the core of aspLite. 

All the other things I have been amusing myself with so far (jszip, rss, atom, hashing, etc) are "nice" utilities, but they are not essential at this point.

Mangius, are you OK with closing this thread for now? Thanks for your feedback. It has helped a lot to get a better idea on how to continue this exciting development.
